// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using dotnet9WebAPI.ai.gen.Models;

namespace dotnet9WebAPI.ai.gen.Models
{
    public partial class ContosoUniversityContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
