// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using dotnet9WebAPI.ai.gen.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace dotnet9WebAPI.ai.gen.Models
{
    public partial class ContosoUniversityContext
    {
        private IContosoUniversityContextProcedures _procedures;

        public virtual IContosoUniversityContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ContosoUniversityContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IContosoUniversityContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ContosoUniversityContextProcedures : IContosoUniversityContextProcedures
    {
        private readonly ContosoUniversityContext _context;

        public ContosoUniversityContextProcedures(ContosoUniversityContext context)
        {
            _context = context;
        }
    }
}
